const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'Fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 3,
      countInStock: 10,
      description: 'A Shirt for everyone',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 130,
      brand: 'Puma',
      rating: 3.9,
      numReviews: 12,
      countInStock: 40,
      description: 'A very distinguished Shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 950,
      brand: 'Puma',
      rating: 2.5,
      numReviews: 2,
      countInStock: 11,
      description: 'Pants fitted for sporting especially golf',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 90,
      brand: 'Nike',
      rating: 2.7,
      numReviews: 21,
      countInStock: 15,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 200,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 7,
      countInStock: 5,
      description: 'A Classic and fitted pants',
    },
  ],
};

export default data;
